### PR TITLE
Add PHP filter for default settings

### PR DESCRIPTION
**Pull request by Luehrsen**
For testing, this is a possible integration of the proposal in #3. 

Works as expected, allthough now I'm getting a 'Uncaught TypeError: e.timeoutFn is not a function'. I believe quicklink expects 'timeoutFn' to be function, but we currently provide string.

I still have to change the JS/Webpack to not recompile quicklink, but just copy the file from the package.

### CODE REVIEW

**Comment by westonruter** [comment]
Would you like me to amend additional commits to this branch?

**Comment by Luehrsen** [comment]
Sure thing, go for it!

**Comment by westonruter** [comment]
> Works as expected, allthough now I'm getting a 'Uncaught TypeError: e.timeoutFn is not a function'. I believe quicklink expects 'timeoutFn' to be function, but we currently provide string.

This should be fixed now.

> I still have to change the JS/Webpack to not recompile quicklink, but just copy the file from the package.

I see in #3 I incorrectly suggested copying `dist/quicklink.js` into the build. Rather, it actually needs to copy `dist/quicklink.umd.js`

**Comment by westonruter** [comment]
> I still have to change the JS/Webpack to not recompile quicklink, but just copy the file from the package.

As part of this, I think the registered script version should be the version of Quicklink, not the version of the plugin. In other words, the build should use this version:

https://github.com/luehrsenheinrich/quicklink/blob/7a6e4806a4f6cbf121dbd345cfde2c786461c6d1/package-lock.json#L11807

Rather than:

https://github.com/luehrsenheinrich/quicklink/blob/7a6e4806a4f6cbf121dbd345cfde2c786461c6d1/package.json#L2

**Comment by Luehrsen** [comment]
@westonruter What would you think about passing the options array with `wp_localize_script` and then do the parsing of that array and the calling of quicklink in a new wp-quicklink.js file?

**Comment by westonruter** [comment]
@Luehrsen I don't think we should introduce a new JS file that is loaded. Loading one external script `quicklink.js` is bad enough in that it is blocking. I've opened https://github.com/GoogleChromeLabs/quicklink/issues/81 to eliminate the need to load `quicklink.umd.js` synchronously. True this could be avoided by just continuing to do what you already have with having Webpack import `quicklink` and then call it. Maybe that would be ultimately a better approach, which would be similar to what you suggest, except there would still just be one JS file.

So:

1. Export the `$options` from PHP to JSON via:

```php
wp_add_inline_script( 'quicklink', sprintf( 'var quicklinkOptions = %s;', wp_json_encode( $options ) ), 'before' );
```

Using `wp_add_inline_script()` is preferable to `wp_localize_script()` because it casts scalar values (e.g. booleans and numbers) to strings (see [#25280](https://core.trac.wordpress.org/ticket/25280)).

2. Update `build/js/quicklink.js` to not export `quicklink` but to rather invoke `quicklink()` after converting converting the PHP-exported data into the object properties that Quicklink requires. So this would move 

So this would move the following code into `build/js/quicklink.js`:

https://github.com/luehrsenheinrich/wp-quicklink/blob/b25dd8372ab8af49f966ac42e6da3e28c6f8fd05/build/quicklink.php#L110-L134

For example:

```js
import quicklink from "quicklink/dist/quicklink.mjs";

document.addEventListener( "DOMContentLoaded", () => {

    const options = Object.assign( {}, window.quicklinkOptions );

    /* Convert selector into element reference. */
    if ( options.el ) {
        options.el = document.querySelector( options.el );
    }

    /* Convert strings to regular expressions. */
    if ( options.ignores ) {
        options.ignores = options.ignores.map( function( ignore ) {
            return new RegExp( ignore );
        } );
    }

    /* Obtain function reference. */
    if ( options.timeoutFn ) {
        var timeoutFnName = options.timeoutFn;
        options.timeoutFn = function() {
            // @todo timeoutFnName should really allow for referencing object properties, like 'myLib.foo.bar.callback'.
            return window[ timeoutFnName ].apply( window, arguments );
        };
    }

    quicklink( options );
} );
```

An added benefit here is that we could eventually then filter `script_loader_tag` to add the `async` attribute to the enqueued script.

**Comment by Luehrsen** [comment]
@westonruter Looks really good to me!

If you want to give an approval here I could merge and push a new version to the wp.org repo.

**Comment by Luehrsen** [comment]
Ah, I'm still getting a type error with the timeoutFn and the quicklink is not working on my end. Do you see that as well? 

I'll try to debug that over the weekend. 

https://github.com/luehrsenheinrich/wp-quicklink/blob/d8efb357a4ecb6e05c3ada9e480e3f62f123c171/build/js/quicklink.js#L24

**Comment by westonruter** [comment]
Give f31cdc8 a try, but beware that I made the change via my phone 😀

**Comment by westonruter** [comment]
Maybe I shouldn't have changed the `apply` logic because we should keep the context as `window`.

**Comment by westonruter** [comment]
OK, I think it's good now!

**Pull request merged**
